### ISSUE TITLE
Stop function

### ISSUE THREAD

**Issue by Mikha495** [onfoot/homebridge-shelly-shutter#2]
Any possibility to integrate a stop function? Would like to have an option in HomeKit of stopping the movement of the shutter, rather than inverting it.

**Comment by onfoot** [comment]
Actually I did implement a stop function, but I guess Home app doesn't expose it :(

**Comment by Mikha495** [comment]
How would the stop be triggered in your implementation?

Point is, I‘m using a Aqara wireless  double button switch to control one of the shades. Connected through HomeKit. There I can’t set a percentage of closing/opening. It just goes full open or full closed, or a preconfigured percentage.

**Comment by onfoot** [comment]
There is a Shelly API call that tells the shutters to stop, and there's a Hold Position functionality of HomeKit's window covering accessory. I use both, but only custom HomeKit apps expose it, like the Elgato Eve app.

**Comment by onfoot** [comment]
Yeah, I just checked - you can assign the Hold action to a HomeKit button in Elgato Eve app, so let me know if it works. :)

**Comment by Mikha495** [comment]
Yes, you are right. It works through the Eve app. 
Thanks a lot!:)
