### ISSUE TITLE
Latest firmware update broken plugin

### ISSUE THREAD

**Issue by Ipnotik** [onfoot/homebridge-shelly-shutter#4]
Hello,
this morning I had the great idea to update the firmware for my shelly 2.5 Since then your plugin doesn't work anymore. Please help!

**Comment by onfoot** [comment]
Will get on it as soon as I'm back home from vacation today!

**Comment by Ipnotik** [comment]
According to firmware release: "Shelly2.5 - switch status is reported by CoAP"

**Comment by Ipnotik** [comment]
OK I think to have fixed the problem. I just redid a position calibration within shelly app and everything went back to normal.

**Comment by onfoot** [comment]
Cool, good to know!
