### ISSUE TITLE
Problem with more than 1 Shelly 2.5

### ISSUE THREAD

**Issue by macguru341** [onfoot/homebridge-shelly-shutter#5]
Hello
I’m getting an error when adding in my config file another 2 Shelly I have , when I put only one everything is working fine but when I’m adding the other 2 I get an error in my config file.
What is the right way to add another Shelly in the config file?

**Comment by onfoot** [comment]
You need to make sure that the "name" parameter is unique for each Shelly you add in the config.

So the "accessories" section of the config looks something like this:

```
"accessories": [
  {
    "accessory": "shelly-shutter",
    "name": "Porch",
    "ip": "192.168.0.190"
  },
  {
    "accessory": "shelly-shutter",
    "name": "South Window",
    "ip": "192.168.0.191"
  },
  {
    "accessory": "shelly-shutter",
    "name": "North Window",
    "ip": "192.168.0.192"
  }
]
```

**Comment by macguru341** [comment]
Thanks it helped a lot
