### ISSUE TITLE
No stop option?

### ISSUE THREAD

**Issue by macguru341** [onfoot/homebridge-shelly-shutter#6]
Hello
I know that this issue was discussed before but I looked into it and I understand that there’s no solution for using the HomeKit app to stop the movement of the shutter.
I would like to ask if you are planing to add this option in the next version ? I think that the invert can kill the motor so I’m afraid that my wife will kill me if this will happen :) 
Is there a way to add this to this plugin? Or any alternative? 
Thanks

**Comment by onfoot** [comment]
Yeah. Home app doesn't support the stop shutters command, but the custom ones do, like Eve Home, which I, admittedly, rarely use, because it's not right in Control Center. ;)

I guess I *could* implement a switch that is on when shutters are moving, and which you can turn off to stop them. When shutters are stopped, turning it on could move the shutters in the opposite direction depending on their position (closed or almost closed? open! opened or almost opened - close!). Could be an alternate way of controlling them, actually. Huh. Something to think about.

**Comment by onfoot** [comment]
So, you can check out the updated plugin, 0.0.7. It contains the feature I described above, with the difference that the "move" control will simply open or close the shades depending on the last moving direction, not whether they were mostly closed or mostly opened. I was doing some testing and it felt better to have a simpler toggle. But we can always change that. :)

**Comment by Nastras** [comment]
How can I deactivate the toogle switch?

**Comment by onfoot** [comment]
You mean you'd like to remove it?

**Comment by Nastras** [comment]
Yeah, exactly, I don't need that switch. Is it possible to remove it via config.json?

**Comment by onfoot** [comment]
Not currently, but I'll add that option, sure.

**Comment by Nastras** [comment]
That would be great! Thank you!

**Comment by onfoot** [comment]
Here you go. v0.0.8 is available.

The option to enable the switch is 'move-toggle' with either `true` or `false`. The default is `false`, so you can omit the option completely if you don't need this functionality.

**Comment by Nastras** [comment]
Hello, it's working. The toggle switches are no longer displayed. 
Thanks for your great work and the great plugin!

**Comment by Pato84s** [comment]
> So, you can check out the updated plugin, 0.0.7. It contains the feature I described above, with the difference that the "move" control will simply open or close the shades depending on the last moving direction, not whether they were mostly closed or mostly opened. I was doing some testing and it felt better to have a simpler toggle. But we can always change that. :)

Hello,
thank you for the amazing plugin!

The toggle stop works perfectly, it would be possible to add 3 buttons?  
1) go up 
2) go down 
3) stop
such as the original Shelly application?

Thank you!
