### ISSUE TITLE
Add basic auth

### ISSUE THREAD

**Issue by funkyremi** [onfoot/homebridge-shelly-shutter#8]
Hey, thanks for your work on this plugin.
Could you please add basic auth for password protected Shelly?

**Comment by onfoot** [comment]
Yep! That crossed my mind recently. Sorry the plugin seems a bit stale - I actually have been working on it in the past few days! Will get on the basic auth as soon as I'm done with some status tweaks, #6 and #7 .

**Comment by onfoot** [comment]
Check out plugin version 0.0.7, codename Shellies are forever. 🔫🍸👙🇬🇧

**Comment by funkyremi** [comment]
Omg you’re awesome 😎 👏
